name: 'sports_betting_intelligence'
version: '1.0.0'
config-version: 2

profile: 'sports_betting_intelligence'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  sports_betting_intelligence:
    +schema: seeds

models:
  sports_betting_intelligence:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: mart
      +materialized: table
